### ISSUE TITLE
HOME PAGE - TABLET numbers missing

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#106]
the slider is perfect now. :) 
the only thing that is missing are the numbers from 3 til 5. if you press number 3 or bellow its taking you to 3rd section of home page but the numbers are dissapearing and you cannot return back by click. You can slide.
again the slider now is perfect on tablet- its smooth - 
pls just check the numbers

**Comment by codephobe** [comment]
@alexandru-b Please check this. I can see the problem on staging but it's working fine on my site: http://jaketom.me/work/w3site6/home.html

**Comment by alexandru-b** [comment]
yes, fixed!
