### ISSUE TITLE
HOME PAGE - TABLET/MOBILE Social buttons

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#107]
tablet - they are not in one line they are in two
mobile  -they are to small and to close one to each other

**Comment by gridsoft** [comment]
here are form other page
![screenshot_2015-10-04-11-58-04](https://cloud.githubusercontent.com/assets/9592326/10267723/22c55558-6aa0-11e5-8f94-fed31e2f0438.png)

its the same on mobile home page

**Comment by codephobe** [comment]
Fixed on homepage. Please test and if it's fine now, will apply to rest of the pages.

**Comment by codephobe** [comment]
Fixed on all pages.
