### ISSUE TITLE
HOME PAGE - TABLET/MOBILE - JUST SUGGESTION

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#108]
this is from my point of view. take it only as a suggestion.
the ampty space that is left between the section is to big. when you slide you are sliding to much from one content to other ( from one section of page - 2 lets say to another 3rd one for example)
if its not changing anything and not taking much time i will consider making the sections for tablet and mobile little bit closer one to another

JUST a suggestion

**Comment by codephobe** [comment]
A picture is worth a thousand words.

**Comment by gridsoft** [comment]
will try to take picture and send you
