### ISSUE TITLE
TABLET/MOBILE - case study pictures link

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#111]
– pictures/links for viewing case studies are missing. If you click on pictures nothing – not linking to case study

when you press on picture it shuold open a case study like in desktop version of the same page.

cannot check the case study page on mobile and tablet, so pls fix it and let me know when done to test them.

**Comment by codephobe** [comment]
Linking issue.

**Comment by alexandru-b** [comment]
@gridsoft fixed, you can test now.

**Comment by gridsoft** [comment]
did test ther are not working
Iphone5, safary browser

![case studies footer bar aligment](https://cloud.githubusercontent.com/assets/9592326/10287201/091bca9a-6b92-11e5-997f-adea9dcd6a26.JPG)

I`m taking about this case study - pictures - if you pressed them it should link you to that case study page

**Comment by alexandru-b** [comment]
@gridsoft  this is fixed now
