### ISSUE TITLE
CASE STUDY - plugin

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#112]
section with Mobile in hand not working. text what we did missing next to the hand  – checked on desktop since I cannot access with tablet and mobile

![what we did](https://cloud.githubusercontent.com/assets/9592326/10264484/149a0b4c-6a0d-11e5-9526-263cd43b0971.JPG)

**Comment by codephobe** [comment]
Working on my site: http://jaketom.me/work/w3site7/case-study.html

**Comment by alexandru-b** [comment]
@gridsoft please clear cache. If problem persis please give me following info:
Link to the page:
Browser:
OS:
