### ISSUE TITLE
ALL Platforms - insights page - all categories

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#115]
When you press on all categories under search criteria - empty white page is been shown
te rest of the categories filter are working fine

**Comment by codephobe** [comment]
Wp issue.

**Comment by alexandru-b** [comment]
@gridsoft link & screenshot where you click?

**Comment by gridsoft** [comment]
Ok will post.

**Comment by gridsoft** [comment]
thisis the link 
http://staging13.worlddigital.com.au/insights/

desktop version firefox browser

![all](https://cloud.githubusercontent.com/assets/9592326/10286220/fc2d3eb8-6b8c-11e5-9a04-c73e12f1a580.JPG)

here is the screenshot

**Comment by gridsoft** [comment]
bobi : OK checked its working, but I cannot test the filter now since all of issues are put Uncategorized
