### ISSUE TITLE
Desktop - blog - published in

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#117]
![text missing](https://cloud.githubusercontent.com/assets/9592326/10264507/cff573d6-6a0d-11e5-802a-63ccaf892ae7.JPG)

Published in: categories text  missing– under author picture bellow the lined in and tweet buttons

**Comment by codephobe** [comment]
Not displaying as on my site: http://jaketom.me/work/w3site7/insights-and-article-content.html

![rob](https://cloud.githubusercontent.com/assets/8403041/10268001/94395212-6ab3-11e5-838b-f2f0ab57cb17.PNG)
