### ISSUE TITLE
mobile - navbar - active page state

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#127]
Icons will have a filled in element to indicate active pages

**Comment by codephobe** [comment]
Wp.

**Comment by alexandru-b** [comment]
@gridsoft please explain

**Comment by gridsoft** [comment]
Active page. When you are on certain page "insights" for example the "insights button on navigation bar should be different from others. Either darker or whatever like pressed btn.
something like this

![this](https://cloud.githubusercontent.com/assets/9592326/10286330/84ab2214-6b8d-11e5-9f8b-7b0a893bddc6.JPG)
