### ISSUE TITLE
SERVICE - MOBILE - wrong title format

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#131]
should be like this

![how we work](https://cloud.githubusercontent.com/assets/9592326/10267393/a9d36b2e-6a92-11e5-9ce1-73e6959a18b6.JPG)

"how" should not be underlined and should be moved in up column

**Comment by codephobe** [comment]
Fixed.

**Comment by gridsoft** [comment]
![img_0981](https://cloud.githubusercontent.com/assets/9592326/10286714/77bb031a-6b8f-11e5-84c5-6c38e2dabc81.PNG)

this is on staging today. no underline at all
@srsjake ; @alexandru-b

**Comment by gridsoft** [comment]
bobi:ok -fixed
