### ISSUE TITLE
leadership page  - wrong text

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#137]
Our (not so) secret power - text should be 
instead of 
"Our team is made up of doers, thinkers and builders. When you've got a team of dreamers that can get things done and can back it up with numbers, not even the sky is the limit."

 in this part the text in filed should be

"After decades in the industry, the leadership team at W3 know the power of utilising
data to empower and delight customers. They have teamed up to bring this knowledge to
the world."

**Comment by codephobe** [comment]
Fixed.
