### ISSUE TITLE
mobile - leadership photos

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#138]
check the picture attached. the final picture is being covered bu text our not so....

![screenshot_2015-10-04-11-30-45](https://cloud.githubusercontent.com/assets/9592326/10267648/2c025642-6a9c-11e5-9220-9ec0f833a212.png)

pls check the number of photos as well

**Comment by codephobe** [comment]
Not like this on my site: http://jaketom.me/work/w3site7/about-us.html

**Comment by alexandru-b** [comment]
@srsjake yes, it's true that on your site is not like this, but in the future please consider that height of the blocks where content is added by the client may vary, so don't use a fixed height.
