### ISSUE TITLE
blog - read more button align

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#139]
I think that the blog sections should be all aligned
the read more buttons should be in same line everywhere
not like this

![blog align](https://cloud.githubusercontent.com/assets/9592326/10267675/8770445c-6a9d-11e5-9b0b-61e1a6d966d2.JPG)

@alex; @srsjake i think you might know better

**Comment by codephobe** [comment]
Depends on the content. This is correct.
