### ISSUE TITLE
mobile - insight - newsletter sign up

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#140]
the newlseter sign up is missing from page 
there should be according to design
![newsleter sign up-mobile](https://cloud.githubusercontent.com/assets/9592326/10267695/894cdb5e-6a9e-11e5-8342-5238212f0fe8.JPG)

**Comment by codephobe** [comment]
This is the tablet header. It's not in the designs for mobile. They used the wrong image in the annotations. Please cross check these things for consistency in the future.
