### ISSUE TITLE
All platforms: On the News letter pop-up, there should be an “envelope” image, on top of the "Be in the Know” text 

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#148]
On the News letter pop-up, there should be an “envelope” image, on top of the "Be in the Know” text 
![screen shot 2015-10-05 at 9 21 37 pm](https://cloud.githubusercontent.com/assets/9592326/10289643/141181a4-6ba8-11e5-8924-9031fae5efe8.png)
The “*” on the Newsletter pop-up should be red

**Comment by codephobe** [comment]
The camera is a placeholder image because no image was provided.
