### ISSUE TITLE
All platforms: On the bottom page of Services there are some “????” in text 

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#149]
The combined ???? of these capabilities help us create better experiences for your customers.
![screen shot 2015-10-05 at 9 30 23 pm](https://cloud.githubusercontent.com/assets/9592326/10289688/4c8e11c8-6ba8-11e5-974e-3d91606a63fa.png)

**Comment by codephobe** [comment]
This is as per design.
