### ISSUE TITLE
Desktop: On the main menu “Case studies” should be a hover over, but its not.

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#152]
According to the Specifications, this should be a hover over. 
"Hover effect showing short description, link to case study"

**Comment by codephobe** [comment]
It says hover and click, had to choose one of the two.

![hoverclick](https://cloud.githubusercontent.com/assets/8403041/10299859/0ce646e4-6bf8-11e5-81b2-d36c645917bc.PNG)
