### ISSUE TITLE
Desktop: Items on the Insight page are not aligned 

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#156]
The items on the Insights page should be truncated so all articles are aligned. Now they look like they have been randomly placed there.

![screen shot 2015-10-05 at 11 02 35 pm](https://cloud.githubusercontent.com/assets/9592326/10291970/3a2f3202-6bb5-11e5-8460-d9d78e2a6430.png)

**Comment by codephobe** [comment]
This is wp specific but as you can see, they are aligned along the top. The issue arises because the whole blog title is displayed and this is variable as per blog post so I'm not sure how alex would go about fixing it.
