### ISSUE TITLE
All platforms: Issues on the Insights -> Article page 

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#159]
Go to Insights page and click "Read more" for an article:
1. The article title is written in Capitalized letters and only the first letter from the title should be Capitalized 
2. The search is grey and it should be white - also, the text "Search" should not be present 
3. Feed button is missing 
   ![screen shot 2015-10-05 at 11 30 53 pm](https://cloud.githubusercontent.com/assets/9592326/10292660/24b6735a-6bb9-11e5-88b6-1a5082f827ce.png)
4. Tags have the "default link" color, they don't have the "designed" color 
   ![screen shot 2015-10-05 at 11 31 15 pm](https://cloud.githubusercontent.com/assets/9592326/10292669/308cd174-6bb9-11e5-9efd-e7c88446dea9.png)
5. On the bottom of the page, the arrow is missing from the "Sign me up" button 
   ![screen shot 2015-10-05 at 11 30 09 pm](https://cloud.githubusercontent.com/assets/9592326/10292656/1565590c-6bb9-11e5-8e27-908c11647a60.png)
6. According to the mock-up, the Read More buttons should be Grey not Blue 
7. The articles on the bottom of the page are not aligned. The first one is upper than the rest 
   ![screen shot 2015-10-05 at 11 41 41 pm](https://cloud.githubusercontent.com/assets/9592326/10292963/a5ea8d7a-6bba-11e5-87cc-875017a737c8.png)

**Comment by codephobe** [comment]
Appears correct on my site. http://jaketom.me/work/w3site7/insights-and-article-content.html
Wp issue.
Although, I see that the read more buttons on staging are not blue but grey as per designs?

**Comment by alexandru-b** [comment]
@srsjake not everything...just 6 & 7 where the same

**Comment by gridsoft** [comment]
@srsjake 
it is not done
