### ISSUE TITLE
tablet:blog long content 

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#165]
check the picture from bottom up

![image](https://cloud.githubusercontent.com/assets/9592326/10294880/38c7fda6-6bbd-11e5-8dc9-b03f329449fd.png)
![image](https://cloud.githubusercontent.com/assets/9592326/10294879/38c76526-6bbd-11e5-81f1-e7941bfd780a.png)
![image](https://cloud.githubusercontent.com/assets/9592326/10294878/38c1187e-6bbd-11e5-912a-c4ab2dea67f9.png)

check the pic. for longer case studyes, the sign in form is been shown over the content covering part of it, and than the content continues after.

**Comment by codephobe** [comment]
Couldn't replicate on my site.

**Comment by alexandru-b** [comment]
@srsjake add a lot of content and it will happen! Again as an advice, never use fixed height when the content is variable.
