### ISSUE TITLE
Mobile: The layout for the Insights page is wrong 

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#166]
1. "Search" text should not be displayed 
2. All the categories should be individual tabs 
3. You should be able to scroll between the categories 
4. Search box exceeds  the page layout 
5. Feeds button is missing 
6. The articles should be on one column, not on two 
   ![img_7009](https://cloud.githubusercontent.com/assets/9592326/10294970/127bccf0-6bc6-11e5-90cc-7b840b9d440a.png)

**Comment by codephobe** [comment]
1. Fixed.
   2,3. Could not implement slider but made the sections layout better. Will get back to it in next iteration.
2. Fixed.
3. I believe this is easier through wp?
4. Appears as one column on my site. Alex, please check.
