### ISSUE TITLE
main menu - OUR WORK

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#18]
1. OUR WORK NAVIGATION HOVER
   The only section in the navigation with sub-categories is the 'our
   work' tab. This is how the sub-sections should display on click.

![our work](https://cloud.githubusercontent.com/assets/9592326/10152400/de4a42d2-6651-11e5-9a2f-24c1beeac570.JPG)

**Comment by codephobe** [comment]
Implemented and pushed to github.
