### ISSUE TITLE
TABLET - NAvigation

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#19]
1. NAVIGATION
   Once the window size reaches the width of an iPad, the navigation is
   to become a sticky bar at the bottom of the page.
2. SECTIONAL NAVIGATION
   Due to the lack of room as the site becomes responsive, the active
   stays will stay numerical, but become highlighted with an active
   circle.
3. SUBSCRIBE LINK
   The subscribe section moves to the center with the baseline
   matching that of the Logo and the phone number.

![tablet home](https://cloud.githubusercontent.com/assets/9592326/10152429/25f24562-6652-11e5-8ccd-0586a4d935f2.JPG)

**Comment by codephobe** [comment]
Implemented and pushed to github.
