### ISSUE TITLE
TABLET - case study home page

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#20]
1. CASE STUDY IMAGES
   The case study sections only show the two latest case studies
   rather than three (based on the featured category) as the site
   becomes responsive.
2. BUTTON ALIGNMENT
   Buttons become left aligned

![case tablet](https://cloud.githubusercontent.com/assets/9592326/10152447/4ea61c5e-6652-11e5-8e80-a2c99e0fe9b0.JPG)

**Comment by codephobe** [comment]
Implemented.
