### ISSUE TITLE
TABLET our work sub menu

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#21]
![our work tablet](https://cloud.githubusercontent.com/assets/9592326/10152456/7e5de206-6652-11e5-8a5e-1454f3790f87.JPG)
1. OUR WORK TABLET NAVIGATION
   The sub-nav items under our work should appear like this on tablet
   sized devices. The section should slide up from under the nav items
   smoothly.

**Comment by codephobe** [comment]
Styles implemented. Sliding effect will be handled through wp similar to issue #24.
