### ISSUE TITLE
MOBILE naviagtion

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#22]
![mobile](https://cloud.githubusercontent.com/assets/9592326/10152469/ab2d91dc-6652-11e5-8b49-a78ce6502d68.JPG)
1. NAVIGATION
   The navigation converts into 4 clickable panels on mobile, with the
   3 more important pages visible, and the rest of the pages to show
   when the "More" button is clicked.
2. MORE BUTTON
   The newsletter nav and remaining navigation items will appear in
   here. Once touched, a panel will expand up showing the navigation
   list.

**Comment by codephobe** [comment]
Done and linked with issue #24.
