### ISSUE TITLE
TABLET - OUR WORK / who we work with sub-menu

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#29]
1. FILTERS
   Once filters reach the break point, they'll convert into a slide-able
   section allowing you to swipe left and right through different filters
   before toggling them.
2. POP-UPS
   Pop-ups will be the same for all devices (Desktop to mobile).
   If a square has "View Case Study", clicking the tile will take them to
   the actual relevant case study. If no case study is available, a pop-up
   will appear prompting the user to get in touch with us.
3. POP-UP LOGOS
   The relevant logo to what was clicked will need to be called into the
   modal.

![popups](https://cloud.githubusercontent.com/assets/9592326/10152613/56a39fb0-6654-11e5-913b-80f1f2c2800f.JPG)

**Comment by codephobe** [comment]
1. The styling of the filter menu on tablet and mobile has been replaced with a simpler, temporary layout for now. The challenge lies in the fact that it's hard to find a single plugin that takes care of all the filtering AND the responsive menu slider features. So I prioritized the former.

2, 3. Working on popups now.

**Comment by codephobe** [comment]
2, 3. Fixed and pushed to github.
