### ISSUE TITLE
DEsktop - Case study

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#30]
1. IMAGES
   There'll only be one featured image displayed.
2. BACKGROUND COLOUR FOR INTRO
   A colour selector to control the background will be needed to allow
   us to change the background to reflect the clients brand colours. By
   default, the colour will be the Working Three blue.
3. SLIDER FUNCTIONALITY
   The slider is to be a toggable feature through the back-end. If the
   slider option has been toggled, the ability to upload slider images
   should appear, and allow us to upload the slider images. (These will
   be just the mobile screenshots). They should appear in the layered
   hand which will be provided.
   If the slider option is not toggled, the ability to be left blank, or
   upload a static image should appear. The static image will not be
   displayed in a mobile, or have the hand.

![case study desktop](https://cloud.githubusercontent.com/assets/9592326/10152685/3247b0f6-6655-11e5-8c12-a57084a93286.JPG)

**Comment by codephobe** [comment]
Discussed with Alex, assign to him.
