### ISSUE TITLE
DEsktop - case studies

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#32]
1. LOGO IS TO BE UPLOADED AS A SEPERATE IMAGE TO THE
   THUMBNAIL IMAGE.
   This is so that the logo can be transitioned out on hover without
   affecting the background image.
2. BACKGROUND BLUR
   Background is to blur on the thumbnail when the tile is hovered over,
   with a subtle black overlay appearing over the image.

![case desk](https://cloud.githubusercontent.com/assets/9592326/10152736/a32aa148-6655-11e5-813e-90ea7c7271ec.JPG)

**Comment by codephobe** [comment]
Will get to it after fixing my pages.

**Comment by codephobe** [comment]
Fixed.
