### ISSUE TITLE
Desktop - Leadership

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#33]
1. LONG PAGES REQUIRE SECTIONAL NAVIGATION
   Like the homepage, this page will require a sectional navigation list.
2. COLOURS
   Each section will be a selected colour from the brand colours. These
   colours should match the relevant sections from the Home Page.
3. LAYOUTS VARIATIONS
   Page structures will rarely change - so each different sections may
   need custom fields (page specific) to allow the different column
   layouts.
4. ALTERNATIVE SECTION COLOURS
   For long pages, there'll need to be a sectional colour difference to
   help divide page sections up.
5. PROFILES
   There'll be three profile categories - Board, Leadership and Seniors.
   They will need to have the ability to enter/upload the following:
6. Profile Image
7. Name
8. Job title
9. Personal Linked In URL, and personal Twitter URL (These will be
   optional fields, and will display if one of these members creates a
   blog post).

![leadership](https://cloud.githubusercontent.com/assets/9592326/10152791/1a510258-6656-11e5-94af-5d598e141c7b.JPG)

**Comment by srsjake** [comment]
Where are these requirements detailed? I followed the designs provided. This is extra work.

**Comment by srsjake** [comment]
This is a sizable refinement, will get to it last.

**Comment by codephobe** [comment]
Everything implemented from my side. Points 5-9 should be managed through wp.

**Comment by gridsoft** [comment]
PROFILES There'll be three profile categories - Board, Leadership and Seniors. They will need to have the ability to enter/upload the following:
Profile Image
Name
Job title
Personal Linked In URL, and personal Twitter URL (These will be optional fields, and will display if one of these members creates a blog post).
