### ISSUE TITLE
Desktop - BLOG

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#34]
1. INTRO SECTION
   This is the same copy to be used in the excerpt (of course, with
   the excerpts limiting the character count). This will need to be in
   a seperate WYSIWYG editor, with the standard content appearing
   below.
2. BLOCK QUOTES
   These sections will just be block-quotes.
3. SOCIAL ICONS
   These are to stack horizontally and become sticky once you scroll.

**Comment by codephobe** [comment]
Will get to it after fixing my pages.

**Comment by codephobe** [comment]
Fixed.
