### ISSUE TITLE
DEsktop - INSIGHTS / blog

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#37]
1. BLOG CATEGORIES
   There'll only be four blog categories. Each link will be related to a
   colour. They are as follows:
2. Insights : Green
3. Strategy : Purple
4. Design : Blue
5. Technology : Yellow
6. BLOG IMAGES
   At this stage, no blog images will be used.

**Comment by codephobe** [comment]
Alex's page, will get to it after my pages.

**Comment by codephobe** [comment]
Already discussed in previous issue. Will be handled through wp.
