### ISSUE TITLE
1,2,3,4,5 buttons on home page

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#4]
on firefox browser.
here what is happening. when you are on page 3 pres for example page 4(button 4) the page is moving down, than up again and than placing the correct page again. 
check what can be the problem.

**Comment by gridsoft** [comment]
I notice now as well. especially when you are at 5th section of hoe page. press number one and dont move the mouse you will see page going up/down for couple of times and than stoping at selected section )1st one in this case)

**Comment by codephobe** [comment]
Where are you testing?

Please test it here: http://jaketom.me/work/w3site4/home.html

The scrolling function has been disabled for the side navigation buttons. It should just switch instantly. If you're seeing this crazy scrolling on the staging area, it's because my latest updates haven't been pushed to staging.

**Comment by gridsoft** [comment]
on staging server.
tell me where to proceed with the tests. bcs I`m testing on staging and not working there. its fine at your link.
so dont know where to proceed :)

**Comment by codephobe** [comment]
Ask Champ. It's probably just a matter of time until he pushes the most recent updates to staging. I'm here to help if there are any complications with that. All the latest updates should be on staging.

**Comment by gridsoft** [comment]
pls double check if this will work on staging after @champ confirm that everithing is been put on staging. today i still got the same issue

**Comment by codephobe** [comment]
Closing now as the fix has been pushed to github. Reopen if there are issues on staging after applying the fix.
