### ISSUE TITLE
Home Page - navigation item/logo 2

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#40]
![navigation menu site](https://cloud.githubusercontent.com/assets/9592326/10172189/4ed3cd3e-66de-11e5-9675-bcf3c5384721.JPG)

these is how the navigation/main menu be

and this is how i is now

![navigation menu how it is](https://cloud.githubusercontent.com/assets/9592326/10172212/72b7bbfc-66de-11e5-8458-ef579143717c.JPG)

there is already issue about this explaining how it should be. but again here is the explanation
1. OUR WORK NAVIGATION HOVER
   The only section in the navigation with sub-categories is the 'our
   work' tab. This is how the sub-sections should display on click.

**Comment by codephobe** [comment]
This has been implemented. Needs to be pushed to staging.
