### ISSUE TITLE
CASE STUDY - DESKTOP - REMOWE THE YELLOW PART

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#42]
![case study yellow part](https://cloud.githubusercontent.com/assets/9592326/10174379/d65cffcc-66e9-11e5-937c-df32c0155529.JPG)
here is how it is
here is how it should be
![case study yellow part designs](https://cloud.githubusercontent.com/assets/9592326/10174404/ef751350-66e9-11e5-97bc-b4daa1f9cfc6.JPG)

**Comment by codephobe** [comment]
Fixed
