### ISSUE TITLE
wrong text

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#48]
![pop email](https://cloud.githubusercontent.com/assets/9592326/10175031/1b3a41b0-66ed-11e5-8a31-2ef0aaacb07c.JPG)
![pop email](https://cloud.githubusercontent.com/assets/9592326/10175032/1f6e8b6a-66ed-11e5-82af-136a8ed83601.JPG)

wrong text change it

**Comment by codephobe** [comment]
Which page is this?

**Comment by codephobe** [comment]
@gridsoft ^

**Comment by gridsoft** [comment]
Blog post
