### ISSUE TITLE
TABLET - Navigation 2

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#51]
there is no navigation bar at the bottom of the page like it should be on portratit mode. whole part is missing. did the test on ipad air2 on safari browser

Plus
when you try to navigate with siding upon screen is doing some weird staff similar like desktop version when you pres on alpha-numeric part on left side of the page. going up/down couple of times.
slider is not responsive as it should i guess

plus the numbers that should appear on left site are missing as well

**Comment by codephobe** [comment]
Fixed scrolling.

As for the navigation bar, could you show it to me on a call? I didn't see the issue when you showed it to me earlier.

**Comment by gridsoft** [comment]
it is not present on your site but it is on staging. most probably the recent changes of yoursa re not being pushed on staging server
