### ISSUE TITLE
TABLET - insight/blog

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#52]
there is to much white/empty space between numbers with sliders at the bottom/ bellow the last line of blogs, and the red section of the page/ popup your e-maill.... sign me up

**Comment by gridsoft** [comment]
plus there should be 2 rows not 3  with blogs.
there should be category selection on top of starting the rows with blogs as well

**Comment by gridsoft** [comment]
![blog tablet](https://cloud.githubusercontent.com/assets/9592326/10175706/c12de48e-66f0-11e5-83da-cb93d7e27099.JPG)

**Comment by codephobe** [comment]
Will tend to this after the desktop version is ready to test.
