### ISSUE TITLE
Remaining Feature work

### ISSUE THREAD

**Issue by champsupertramp** [champsupertramp/working-three#6]
Here are some remaining tasks that i remember, feel free to add more:
- [ ] @alexandru-b  Add Newsletter form
- [ ] @alexandru-b  Add Contact form
- [ ] @alexandru-b  Add Dropdown Menu
  - Wait for  @srsjake  to push the template for the dropdown
- [ ] @alexandru-b  Need to update homepage elements with @srsjake latest commit. @srsjake  said there's no big changes just a few elements added for responsiveness.
- [ ]  @srsjake / @alexandru-b  Fix misaligned and overlow post content: http://staging13.worlddigital.com.au/2015/09/discussion-with-catherine-heath-from-huge-inc/
- [ ]  @alexandru-b  Add search page ( no template yet )
- [ ] @alexandru-b  Add 404 page ( no template yet )
- [ ] @gridsoft  Clarify the page and single post templates ( No default template yet, I just use the article content template )
- [ ] @gridsoft Clarify menus links and pages.
  - Our work is linked to  http://staging13.worlddigital.com.au/who-we-work-with/
  - Insights page is using `how we work` template

**Comment by codephobe** [comment]
Closing this for now because we have several issues regarding each element tracked separately. Regarding the search and 404 page, will work on them when layouts are received.
