### ISSUE TITLE
[Tablet/Mobile] Create bottom navigation & More Menu Walkers

### ISSUE THREAD

**Issue by champsupertramp** [champsupertramp/working-three#66]
Please see: 

`/templates/sections/header/section-more-menu.php`

`/templates/sections/header/section-nav-bottom.php`

**Comment by champsupertramp** [comment]
related:
https://github.com/champsupertramp/working-three/issues/61

**Comment by alexandru-b** [comment]
Implemented in options framework, if I've implemented as a menu walker icons where not changeable, this way client ca change the icons if they want to.
