### ISSUE TITLE
dekstop site - home page #2

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#72]
G should not be underlined  +the font is wrong

![g](https://cloud.githubusercontent.com/assets/9592326/10227067/96837a6a-686b-11e5-85b4-d2b760be4e70.JPG)

**Comment by codephobe** [comment]
The font is the same as on the titles of all the pages. This is a backend issue as the template I provided has the underline as desired.

**Comment by alexandru-b** [comment]
fixed & closed
