### ISSUE TITLE
DEsktop - WHO we work with

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#79]
![who we work with](https://cloud.githubusercontent.com/assets/9592326/10228553/be6731a4-6873-11e5-8417-2dc6580123dd.JPG)
if there is no case study available, a pop-up will appear like in pictue

**Comment by codephobe** [comment]
@alexandru-b This has been implemented already in the markup as div '#No-case-study'

**Comment by alexandru-b** [comment]
@srsjake great, made the js to make it show up on click. One thing, can you please add the x for closing?
