### ISSUE TITLE
Mobile-case studies page

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#89]
here is how its showing Case studies on mobile - htc oneX

![screenshot_2015-10-01-19-00-53](https://cloud.githubusercontent.com/assets/9592326/10230913/1da8434a-6880-11e5-9483-8b012a7abaaf.png)

the fonts are to small, the nav bar, logo are  missing as well

**Comment by alexandru-b** [comment]
related with https://github.com/champsupertramp/working-three/issues/86
