### ISSUE TITLE
mobile - who we work with slider

### ISSUE THREAD

**Issue by gridsoft** [champsupertramp/working-three#93]
![slider](https://cloud.githubusercontent.com/assets/9592326/10231458/200f9108-6883-11e5-977b-ca5175fe1a85.JPG)

slider on who we work page-mobile version should be like in picture
and there is to much empty(white) space between pictures and begging of contact us (black) section

**Comment by codephobe** [comment]
@alexandru-b I tried implementing slick but the styles were conflicting with the plugin I used for the sorting grid. I'm going to proceed with the other issues and come back to this when I'm done with them. If you can find time to implement slick before that, please help.

**Comment by codephobe** [comment]
Fixed.
